server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driveClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect